#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from project import create_project
from device  import list_devices
from config  import get_config
from message import print_INFO, print_WARNING, print_ERROR

# get configuration from arguments
config = get_config()

if config["command"] == "create":
    create_project(config)
elif config["command"] == "list":
    list_devices()
else:
    print_ERROR("Invalid arguments")
